apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "ffc-demo-calculation-service"
  description: |
    Digital service mock to claim public money in the event property subsides into mine shaft. 
    The calculation service subscribes to a message queue for new claims and calculates a value for each claim.
    Once calculated it publishes the value to a message queue.
  annotations:
    github.com/project-slug: DEFRA/ffc-demo-calculation-service
    dev.azure.com/project: DEFRA-FFC
    dev.azure.com/build-definition: DEFRA.ffc-demo-calculation-service
    sonarqube.org/project-key: adp-ffc-demo-calculation-service
  tags:
    - node
    - service-bus
    - private
    - back-end
spec:
  type: backend
  lifecycle: beta
  owner: "group:default/fcp-demo"
  system: fcp-demo-service
  dependsOn:
    - "resource:default/fcp-demo-calculation-queue"
    - "resource:default/fcp-demo-payment-topic"
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: fcp-demo-payment-topic
  description: Payments message topic
  tags:
    - azure-service-bus
    - topic
spec:
  type: message-topic
  owner: "group:default/fcp-demo"
  system: fcp-demo-service
  dependsOn:
    - "resource:default/ADPINFSB01"
