version: '3.4'
services:
  mine-support-calculation-service:
    build: .
    image: mine-support-calculation-service
    container_name: mine-support-calculation-service
    command: sh -c "scripts/wait-for/wait-for mine-support-calculation-message-queue:8161 -- npm run start:watch"
    depends_on:
      - mine-support-calculation-message-queue
    networks:
      - mine-support-calculation
    volumes:
      - node_modules:/usr/src/app/node_modules
      - .:/usr/src/app

  mine-support-calculation-message-queue:
    container_name: mine-support-calculation-message-queue
    image: vromero/activemq-artemis:2.9.0-alpine
    environment:
      ARTEMIS_USERNAME: artemis
      ARTEMIS_PASSWORD: artemis
    networks:
      - mine-support-calculation
    ports:
      - "8161:8161"
      - "5672:5672"
    volumes:
      - message-queue-data:/var/lib/artemis/data
      - message-queue-tmp:/var/lib/artemis/tmp
      - message-queue-etc:/var/lib/artemis/etc
      - message-queue-etc-override:/var/lib/artemis/etc-override
      - message-queue-lock:/var/lib/artemis/lock

networks:
  mine-support-calculation: {}

volumes:
  message-queue-data: {}
  message-queue-tmp: {}
  message-queue-etc: {}
  message-queue-etc-override: {}
  message-queue-lock: {}
  node_modules: