version: '3.4'
services:
  mine-support-calculation-service:
    command:  ./wait-for amq:8161 -- npm run start-watch
    networks:
      - mine-support
      - mine-support-amq
    volumes:
      - node_modules:/usr/src/app/node_modules
      - .:/usr/src/app
    environment: 
      MESSAGE_QUEUE_HOST : "host.docker.internal"

  amq:
    networks:
     - mine-support-amq

networks:
  mine-support:
   external: true
  mine-support-amq: {}
volumes:
  node_modules:
