version: '3.7'
services:
  ffc-demo-calculation-service:
    build: 
      context: .
      target: production
      args:
        REGISTRY: ${DOCKER_REGISTRY}
    image: ffc-demo-calculation-service
    environment:
      CALCULATION_ENDPOINT: http://ffc-demo-calculation-message-queue:9324
      CALCULATION_QUEUE_NAME: calculation
      CALCULATION_QUEUE_URL: http://ffc-demo-calculation-message-queue:9324/queue/calculation
      CREATE_CALCULATION_QUEUE: "true"
      PAYMENT_ENDPOINT: http://ffc-demo-calculation-message-queue:9324
      PAYMENT_QUEUE_NAME: payment
      PAYMENT_QUEUE_URL: http://ffc-demo-calculation-message-queue:9324/queue/payment
      CREATE_PAYMENT_QUEUE: "true"
      DEV_ACCESS_KEY_ID: elasticmq
      DEV_ACCESS_KEY: elasticmq
    volumes:
      - ./server/:/home/node/server/
      - ./scripts/:/home/node/scripts/
      - ./index.js:/home/node/index.js
      - ./package.json:/home/node/package.json

  ffc-demo-calculation-message-queue:
    image: softwaremill/elasticmq

volumes:
  node_modules: {}
