version: '3.4'

# This override file should be used in development environments to
# connect this service to sibling services from other repositories

services:
  ffc-demo-calculation-service:
    command: >
      sh -c "
        scripts/wait-for/wait-for ffc-demo-message-queue:5672 --
        npm run start:watch"
    networks:
      - ffc-demo

networks:
  ffc-demo:
    external: true
