version: '3.7'

# This override file should be used when running this service in isolation
# to provide required sibling services for local testing

services:
  ffc-demo-calculation-service:
    build:
      context: .
      target: development
    command: npm run start:watch
    ports:
      - "3005:3005"
