version: '3.7'
services:
  ffc-demo-calculation-service:
    build:
      context: .
      target: production
    image: ffc-demo-calculation-service
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-demo-calculation-service-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      EVENT_HUB_HOST: kafka:9092
    volumes:
      - ./server/:/home/node/server/
      - ./test/:/home/node/test/
      - ./scripts/:/home/node/scripts/
      - ./index.js:/home/node/index.js
      - ./package.json:/home/node/package.json

  zookeeper:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_PORT: 9092
