version: '3.7'

# This override file should be used in development environments to
# connect this service to sibling services from other repositories

services:
  ffc-demo-calculation-service:
    build:
      context: .
      target: development
    command: npm run start:watch
    networks:
      - default
      - ffc-demo

networks:
  ffc-demo:
    external: true
