version: '3.4'

# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  ffc-demo-calculation-service:
    command: >
      sh -c "
        scripts/wait-for/wait-for ffc-demo-calculation-test-message-queue:5672 --
        npm run test"
    depends_on:
      - ffc-demo-calculation-message-queue
