version: '3.4'
services:
  mine-support-calculation-service:
    networks:
      - mine-support
      - mine-support-amq
    volumes:
      - node_modules:/usr/src/app/node_modules
      - .:/usr/src/app

  amq:
    networks:
     - mine-support-amq

networks:
  mine-support:
   external: true
  mine-support-amq: {}

volumes:
  node_modules:
