version: '3.8'
services:
  ffc-demo-calculation-service:
    build:
      context: .
      target: production
    image: ffc-demo-calculation-service
    container_name: ffc-demo-calculation-service
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-demo-calculation-service-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      CALCULATION_QUEUE_ADDRESS: ${CALCULATION_QUEUE_ADDRESS:-ffc-demo-calculation}${MESSAGE_QUEUE_SUFFIX}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      PAYMENT_TOPIC_ADDRESS: ${PAYMENT_TOPIC_ADDRESS:-ffc-demo-payment}${MESSAGE_QUEUE_SUFFIX}
      PROTECTIVE_MONITORING_URL: ${PROTECTIVE_MONITORING_URL}
