version: '3.4'
services:
  mine-support-calculation-service:
    command: >
      sh -c "
        scripts/wait-for/wait-for mine-support-calculation-message-queue:8161 --
        npm run test"
    volumes:
      - ./test-output:/usr/src/app/test-output

volumes:
  node_modules:
