version: '3.7'
services:
  ffc-demo-calculation-service:
    build: 
      context: .
      target: production
    image: ffc-demo-calculation-service
    depends_on:
      - ffc-demo-calculation-message-queue  
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-demo-calculation-service-local
      APPINSIGHTS_INSTRUMENTATIONKEY:
      MESSAGE_QUEUE_HOST : ffc-demo-calculation-message-queue
      MESSAGE_QUEUE_PORT : 5672
      CALCULATION_QUEUE_ADDRESS : calculation
      CALCULATION_QUEUE_USER : artemis
      CALCULATION_QUEUE_PASSWORD : artemis
      PAYMENT_QUEUE_ADDRESS : payment
      PAYMENT_QUEUE_USER : artemis
      PAYMENT_QUEUE_PASSWORD : artemis
    volumes:
      - ./server/:/home/node/server/
      - ./test/:/home/node/test/
      - ./scripts/:/home/node/scripts/
      - ./index.js:/home/node/index.js
      - ./package.json:/home/node/package.json

  ffc-demo-calculation-message-queue:
    image: vromero/activemq-artemis:2.9.0-alpine
    environment:
      ARTEMIS_USERNAME: artemis
      ARTEMIS_PASSWORD: artemis

volumes:
  node_modules: {}
