version: '3'
services:
  mine-support-calculation-service:
    build: .
    image: mine-support-calculation-service
    container_name: mine-support-calculation-service
    command: npm run start:watch
    ports:
      - "3005:3005"
    volumes:
      - node_modules:/home/node/node_modules
      - .:/home/node

volumes:
  node_modules:
