version: '3'
services:
  mine-support-calculation-service:
    build: .
    image: mine-support-calculation-service
    container_name: mine-support-calculation-service
    command: npm run watch:server
    ports:
      - "3005:3005"
    volumes:
      - node_modules:/mine-support-calculation-service/node_modules
      - .:/mine-support-calculation-service

volumes:
  node_modules:
