version: '3.7'

# This override file should be used when running this service in isolation
# to provide required sibling services for local testing

services:
  ffc-demo-calculation-service:
    build: 
      context: .
      target: development
    command: >
      sh -c "
        scripts/wait-for/wait-for ffc-demo-calculation-message-queue:5672 --
        npm run start:watch"
    ports:
      - "3005:3005"
    depends_on:
      - ffc-demo-calculation-message-queue
      
  ffc-demo-calculation-message-queue:
    ports:
      - "8161:8161"
      - "5672:5672"
