apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.component: {{ .Values.containers.service.name }}
  name: {{ .Values.containers.service.name }}
spec:
  replicas: {{ .Values.replicas }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  strategy: {}
  template:
    metadata:
      labels:
        app.component: {{ .Values.containers.service.name }}
    spec:
      containers:   
      - name: {{ .Values.containers.service.name }}
        image: {{ if .Values.containers.service.registry }}{{ .Values.containers.service.registry }}/{{ end }}{{ .Values.containers.service.image }}:{{ .Values.containers.service.tag }}
        imagePullPolicy: {{ .Values.containers.service.imagePullPolicy }}
        env:                
        - name: NODE_ENV
          value: {{ .Values.environment }}
        - name: MESSAGE_QUEUE_HOST
          value: {{ .Values.containers.service.messageQueueHost }}
        - name: MESSAGE_QUEUE_PORT
          value: {{ .Values.containers.service.messageQueuePort | quote}}
        - name: MESSAGE_QUEUE_TRANSPORT
          value: {{ .Values.containers.service.messageQueueTransport }}
        - name: CALCULATION_QUEUE_ADDRESS
          value: {{ .Values.containers.service.calculationQueueAddress }}
        - name: CALCULATION_QUEUE_USER
          value: {{ .Values.containers.service.calculationQueueUser }}
        - name: CALCULATION_QUEUE_PASSWORD
          value: {{ .Values.containers.service.calculationQueuePassword }}
        - name: PAYMENT_QUEUE_ADDRESS
          value: {{ .Values.containers.service.paymentQueueAddress }}
        - name: PAYMENT_QUEUE_USER
          value: {{ .Values.containers.service.paymentQueueUser }}
        - name: PAYMENT_QUEUE_PASSWORD
          value: {{ .Values.containers.service.paymentQueuePassword }}
        resources:
          requests:
            memory: {{ .Values.containers.service.requestMemory | quote }}
            cpu: {{ .Values.containers.service.requestCpu | quote }}
          limits:
            memory: {{ .Values.containers.service.limitMemory | quote }}
            cpu: {{ .Values.containers.service.limitCpu | quote }}   
        volumes:                      
      restartPolicy: {{ .Values.containers.service.restartPolicy }}
status: {}
