namespaceTopics:
  - name: payment   
    roleAssignments:
      - roleName: 'TopicSender'

namespaceQueues:
  - name: calculation
    owner: 'no'
    roleAssignments:
      - roleName: 'QueueReceiver'
