namespaceTopics:
  - name: payment   
    roleAssignments:
      - roleName: 'TopicSender'

namespaceQueues:
  - name: calculation
    owner: 'no'
    roleAssignments:
      - roleName: 'QueueReceiver'

storageAccounts:
  - name: 'ggtest'
    roleAssignments:
      - roleName: 'DataWriter'
    blobContainers:
      - name: 'ggdoc'        
    tables: 
      - name: 'ggdocmetadata'
