namespaceTopics:
  - name: payment   
    roleAssignments:
      - roleName: 'TopicSender'
  - name: testtopic    

namespaceQueues:
  - name: calculation
    owner: 'no'
    roleAssignments:
      - roleName: 'QueueReceiver'
