{{- include "ffc-helm-library.container-config-map" (list . "ffc-demo-calculation-service.config-map") -}}
{{- define "ffc-demo-calculation-service.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  CALCULATION_QUEUE_NAME: {{ quote .Values.container.calculationQueueName }}
  CALCULATION_ENDPOINT: {{ quote .Values.container.calculationQueueEndpoint }}
  CALCULATION_QUEUE_REGION: {{ quote .Values.container.calculationQueueRegion }}
  CREATE_CALCULATION_QUEUE: {{ quote .Values.container.calculationCreateQueue }}
  PAYMENT_QUEUE_NAME: {{ quote .Values.container.paymentQueueName }}
  PAYMENT_ENDPOINT: {{ quote .Values.container.paymentQueueEndpoint }}
  PAYMENT_QUEUE_REGION: {{ quote .Values.container.paymentQueueRegion }}
  CREATE_PAYMENT_QUEUE: {{ quote .Values.container.paymentCreateQueue }}
{{- end -}}