{{- include "adp-helm-library.container-secret" (list . "ffc-demo-calculation-service.container-secret") -}}
{{- define "ffc-demo-calculation-service.container-secret" -}}
stringData:
  {{- if .Values.appInsights.key }}
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ quote .Values.appInsights.key }}
  {{- end }}
{{- end -}}
