{{- include "adp-helm-library.deployment" (list . "ffc-demo-calculation-service.deployment") -}}
{{- define "ffc-demo-calculation-service.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "adp-helm-library.container" (list . "ffc-demo-calculation-service.container") }}      
{{- end -}}
