{{- template "ffc-helm-library.deployment" (list . "ffc-demo-calculation-service.deployment") -}}
{{- define "ffc-demo-calculation-service.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ template "ffc-helm-library.container" (list . "ffc-demo-calculation-service.container") }}
      volumes:
      - name: health-dir
        emptyDir: {}
{{- end -}}
