- key: NODE_ENV
  value: "production"
- key: APPINSIGHTS_CLOUDROLE
  value: "{{serviceName}}"  
- key: CALCULATION_QUEUE_ADDRESS
  value: "ffc-demo-calculation"
- key: PAYMENT_TOPIC_ADDRESS
  value: "ffc-demo-payment"    
- key: MESSAGE_QUEUE_HOST
  value: "SNDADPINFSB1401.servicebus.windows.net"      
- key: APPINSIGHTS_INSTRUMENTATIONKEY
  value: "36932cc4-12b7-4f0f-bbee-36ba20174390"        
- key: PROTECTIVE_MONITORING_URL
  value: "" 
