environment: development
name: ffc-demo-calculation-service
namespace: ffc-demo
workstream: ffc-demo
image: ffc-demo-calculation-service
imagePullSecret:
labels:
  instance:
  version: 1.0.0
  component: service
container:
  priorityClassName: low
  imagePullPolicy: IfNotPresent
  requestMemory: 30Mi
  requestCpu: 10m
  limitMemory: 60Mi
  limitCpu: 40m
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  restartPolicy: Always
  redeployOnChange: update this field to force a change
  calculationQueueName: calculation
  calculationQueueEndpoint: http://ffc-demo-calculation-message-queue:9324
  calculationQueueRegion: eu-west-2
  calculationCreateQueue: false
  paymentQueueName: payment
  paymentQueueEndpoint: http://ffc-demo-calculation-message-queue:9324
  paymentQueueRegion: eu-west-2
  paymentCreateQueue: false
replicaCount: 1
minReadySeconds: 10
maxSurge: 1
maxUnavailable: 1

livenessProbe:
  initialDelaySeconds: 70
  periodSeconds: 10
  failureThreshold: 3
serviceAccount:
  name: ffc-demo-calculation-service-account
  roleArn:
