name: ffc-demo-calculation-service
namespace: ffc-demo
image: ffc-demo-calculation-service

labels: {}

deployment:
  priorityClassName: low
  minReplicas: 1
  maxReplicas: 3
  cpuThreshold: 80
  memoryThreshold: 80
  minReadySeconds: 5

container:
  memCpuTier: M

livenessProbe:
  initialDelaySeconds: 70
  periodSeconds: 10
  failureThreshold: 3
  script: /home/node/scripts/healthz

aadWorkloadIdentity: true

serviceAccount:
  name: ffc-demo
  roleArn: true
