environment: development
name: ffc-demo-calculation-service
namespace: ffc-demo
workstream: ffc-demo
image: ffc-demo-calculation-service

labels: {}

serviceAccount:
  name: ffc-demo-calculation-service-account

deployment:
  restartPolicy: Always
  priorityClassName: low
  replicas: 1
  minReadySeconds: 5
  redeployOnChange: update this field to force a change
  imagePullSecret:
  runAsNonRoot: true
  runAsUser: 1000

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 30Mi
  requestCpu: 10m
  limitMemory: 60Mi
  limitCpu: 40m
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  messageQueueHost: amq
  messageQueuePort: 5672
  messageQueueTransport: tcp
  calculationQueueAddress: calculation
  calculationQueueUser: artemis
  calculationQueuePassword: artemis
  paymentQueueAddress: payment
  paymentQueueUser: artemis
  paymentQueuePassword: artemis

livenessProbe:
  initialDelaySeconds: 70
  periodSeconds: 10
  failureThreshold: 3
  script: /home/node/scripts/healthz
