environment: development
containers:
  service:
    name: mine-support-calculation-service
    registry:
    image: mine-support-calculation-service
    tag: latest
    imagePullPolicy: IfNotPresent
    requestMemory: 30Mi
    requestCpu: 10m
    limitMemory: 60Mi
    limitCpu: 40m
    runAsNonRoot: true
    runAsUser: 1000
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    restartPolicy: Always   
    messageQueueHost: amq
    messageQueuePort: 5672
    messageQueueTransport: tcp
    calculationQueueAddress: calculation
    calculatonQueueUser: artemis
    calculationQueuePassword: artemis
    paymentQueueAddress: payment
    paymentQueueUser: artemis
    paymentQueuePassword: artemis
replicas: 1
minReadySeconds: 10
maxSurge: 1
maxUnavailable: 1
