environment: development
containers:
  service:
    name: mine-support-calculation-service
    port: 3005
    registry:
    image: mine-support-calculation-service
    tag: latest
    imagePullPolicy: IfNotPresent
    requestMemory: 30Mi
    requestCpu: 10m
    limitMemory: 60Mi
    limitCpu: 40m
    runAsNonRoot: true
    runAsUser: 1000
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    restartPolicy: Always   
    messageQueue: amqp://mine-support-message-service
replicas: 2
minReadySeconds: 10
maxSurge: 1
maxUnavailable: 1
