environment: development
name: ffc-demo-calculation-service
image: ffc-demo-calculation-service
imagePullSecret:
container:
  imagePullPolicy: IfNotPresent
  requestMemory: 30Mi
  requestCpu: 10m
  limitMemory: 60Mi
  limitCpu: 40m
  runAsNonRoot: true
  runAsUser: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  restartPolicy: Always
  redeployOnChange: update this field to force a change
  messageQueueHost: amq
  messageQueuePort: 5672
  messageQueueTransport: tcp
  calculationQueueAddress: calculation
  calculationQueueUser: artemis
  calculationQueuePassword: artemis
  paymentQueueAddress: payment
  paymentQueueUser: artemis
  paymentQueuePassword: artemis
replicaCount: 1
minReadySeconds: 10
maxSurge: 1
maxUnavailable: 1
